import type { IconType } from "react-icons";
import {
  LuAppWindow,
  LuCalendarCheck,
  LuCalendarDays,
  LuCamera,
  LuChartLine,
  LuClapperboard,
  LuCodeXml,
  LuEye,
  LuGlobe,
  LuLayoutDashboard,
  LuMessagesSquare,
  LuMic,
  LuMousePointerClick,
  LuPalette,
  LuPenTool,
  LuPresentation,
  LuPrinter,
  LuRadio,
  LuRotate3D,
  LuShieldCheck,
  LuShoppingBag,
  LuSmartphone,
  LuSmile,
  LuStore,
  LuTarget,
  LuTrophy,
  LuWorkflow,
} from "react-icons/lu";
import type { LandingIconKey } from "@/lib/landing/types";

// Content files name icons by key so they stay plain data (testable in Node).
export const LANDING_ICONS: Record<LandingIconKey, IconType> = {
  strategy: LuTarget,
  video: LuClapperboard,
  mic: LuMic,
  channel: LuMessagesSquare,
  trophy: LuTrophy,
  chart: LuChartLine,
  booth: LuStore,
  program: LuCalendarCheck,
  camera360: LuRotate3D,
  photobox: LuCamera,
  signage: LuPresentation,
  live: LuRadio,
  ux: LuWorkflow,
  ui: LuLayoutDashboard,
  prototype: LuMousePointerClick,
  brand: LuPalette,
  print: LuPrinter,
  handoff: LuCodeXml,
  website: LuGlobe,
  webapp: LuAppWindow,
  mobile: LuSmartphone,
  design: LuPenTool,
  qa: LuShieldCheck,
  store: LuShoppingBag,
  face: LuSmile,
  behind: LuEye,
  plan: LuCalendarDays,
};
